### ISSUE TITLE
No plume on S3 KS-25 Vector

### ISSUE THREAD

**Issue by dmayan-ss** [ValiZockt/RealFuels-Stock#18]
As the title says. If I uninstall RealFuels-Stock and reinstall RealPlumes-Stock, the plume works.

![image](https://user-images.githubusercontent.com/47798902/89743852-a60f2900-da7d-11ea-87f8-ddca722faeca.png)

Thanks

**Comment by ValentinBischof** [comment]
Thank you for reporting, fixed in the master branch.
