### ISSUE TITLE
Engine config ideas

### ISSUE THREAD

**Issue by TotallyNotHuman** [ValiZockt/RealFuels-Stock#4]
Per #2 I put all my ideas here.
I've only looked at Near Future Spacecraft/Launch Vehicles and ReStock+ outside of stock so these items only cover those mods.

### Fuel ratio consistency
- Near Future Spacecraft: Orbital engines are inconsistent with landing engines, which are not consistent with stock configs.

### Engine tweaks
- LV-1(R) should be pressure-fed and/or have unlimited ignitions, since they're basically RCS thrusters bound to throttle controls. Changing them to share propellant configurations with RCS thrusters would be nice too.
- LV-303 (ReStock+) and O-10 might also be better pressure-fed but with limited ignitions.

### Fuel variety
- LV-T15 "Valiant" (ReStock+): add Ethanol75+LOx, hydrolox, and UDMH/NTO
- Mk-1H "Torch" (ReStock+): add Ethanol75+LOx, hydrolox, and UDMH/NTO
- LV-T30/45 "Reliant"/"Swivel": add hydrolox and UDMH/NTO
- UR-1/2 "Galleon"/"Caravel" (ReStock+): add kerolox and UDMH/NTO
- KR-1(x2) "Boar" (ReStock+)/"Twin-Boar": add UDMH/NTO
- 24-77 "Twitch": add MMH/NTO
- UR-137 "Schnauzer" (ReStock+): add hydrolox

**Comment by ValentinBischof** [comment]
Thanks again for you ideas.

Regarding Fuel ratio consistency, i think i'll have too look over this, not only in the Squad Configs, probably more configs were i messed things up.

Now to the engine tweaks: 
* LV-1 (R) sounds like a reasonable change, it hasn't even visible Turbopumps in the model.
* O-10 is configured after the AJ10-190 (OMS), which is indeed a pressure-fed engine, so mistake on my side here.

I try to configure each engine (if possible) according a real-life equivalent, i try not to have that much of fuel mixtures (like the real ones) They are only a few engines that have the capability to run on multiple fuel mixtures. I may be overthinking this, im not in RO here, im still in stock territorial here, so i guess i'll have to leave my thought, on not having that much of multiple fuel mixtures behind. Just one small change i would make here regarding T30/T45:
* I configured the T-30 after the A-6 Redstone Engine (Alcohol/LOx -> Ethanol75/LOx) 
* The T-45 is just an upgrade, with increased thrust and Isp, so this can be changed to be configured after the A-7 Redstone Engine (Hydyne/LOx) with UDMH as a second mixture, which would actually be not that far out of scope, Hydyne is still 60% (?) UDMH.

**Comment by TotallyNotHuman** [comment]
Sure, the one engine to one fuel mixture thing makes sense.

I also just looked at the fuel mixes for CryoEngines, which are internally consistent but not with Squad configs, so I'll let you determine what to do with those since you're looking at them anyways.

I also came up with a way to patch all RCS thrusters to be switchable between cold gas or hypergolic (like stock), so only the LFO RCS need special patches. I can send that in as a pull request if you'd like.

The thrust and mass for some of the orbital engines from Near Future Spacecraft seem to be off as well, I can take care of those in addition to the LV-1(R) and O-10.

**Comment by ValentinBischof** [comment]
Would be interesting to see your way of patching all RCS thrusters, i've already included [this patch update here](https://github.com/ValiZockt/RealFuels-Stock/blob/master/GameData/RealFuels-Stock/000_GlobalPatches/Non_Configured_Parts.cfg#L30) some hours ago (the one i talked in the PR).

The low mass on some engines _were_ intended at first, the mass of engines in KSP are just very high, so i tried balancing it this way, which wasn't a good idea tbh.

**Comment by TotallyNotHuman** [comment]
Looks like we did mostly the same thing, except my HAS block looks like this: `:HAS[@MODULE[ModuleRCSFX]&!MODULE[ModuleEngineConfigs]]`
I decided to have the RCS thrusters default to MMH+NTO since they have the same base thrust, and applying multipliers to that would be easier. I also removed the ReStock+ RCS patches in my branch since the generic patch would have patched them all, and added configs for NFLV RCS blocks.

I know KSP stock engines are disproportionately heavy, but the NFSpacecraft engines specifically seem to be bugged—the 0.625m engine masses more than the 2.5m engine (which is a cluster of 0.625m engines), and the 1.25m and 3.75m engines mass the same. See following:
![image](https://user-images.githubusercontent.com/25298397/87609734-32fdd700-c6b8-11ea-9a39-f7a9ef7a7cf8.png)
![image](https://user-images.githubusercontent.com/25298397/87609748-3beea880-c6b8-11ea-9289-880f77817c12.png)
![image](https://user-images.githubusercontent.com/25298397/87609758-4315b680-c6b8-11ea-9174-44c401e48307.png)
![image](https://user-images.githubusercontent.com/25298397/87609766-4b6df180-c6b8-11ea-81db-8b0e000fedc7.png)

**Comment by ValentinBischof** [comment]
I check for resourceName, due to a high possibility that not every RCS config has a ModuleEngineConfigs. 

I just checked I changed the mass but not the origMass in the ModuleEngineConfigs. Can't check others right now, will report back later.

**Comment by TotallyNotHuman** [comment]
> I check for resourceName, due to a high possibility that not every RCS config has a ModuleEngineConfigs.

The HAS block I showed you checks for the _lack_ of a `ModuleEngineConfigs`, which should cover all unpatched RCS thrusters, but not the patched ones.

> I just checked I changed the mass but not the origMass in the ModuleEngineConfigs. Can't check others right now, will report back later.

No worries, take your time :)
